### ISSUE TITLE
I want to use 5% data to train the model, but I stick in a problem

### ISSUE THREAD

**Issue by happycjksh** [swiseman/neighbor-splicing#4]
Hello, I want to train a model through 5% training data. However, when I change the length of self.train_srcs, self.train_tgts and self.train_moves into self.train_srcs[:int(len(self.train_srcs)*0.05)], self.train_tgts[:int(len(self.train_srcs)*0.05)] and self.train_moves[:int(len(self.train_srcs)*0.05)], the IDE occurs the error as you can see in the picture. I print the neidx and find the value is 35192, but the length of self.train_srcs is smaller than 35192. So, if I want to use 5% data to train the model, whether I made some mistakes or I should change other variables rather than the up mentioned variables.

**Comment by happycjksh** [comment]
![F8295660F66842078731DEE8C84ABA58](https://user-images.githubusercontent.com/59444174/148387605-8498a40b-fe6e-4edc-adcd-645232a24357.png)

**Comment by swiseman** [comment]
`train_tgts` is used to store all the neighbors, so if you truncate it you will get the indexing error you see (since the oracle moves expect all the training neighbors to be there). If you don't plan on changing the pre-calculated neighbors or derivations, I think you can just truncate `train_srcs` and `train_moves`.
